#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
ROOT_TSX="src/routes/__root.tsx"

banner "Bing Webmaster Tools setup"

# ── Stage 1: add the site ─────────────────────────────────────────────────
stage "Add your site to Bing"
say "We'll register neelapsychology.co.za with Bing Webmaster Tools."
open_url "https://www.bing.com/webmasters/about"
step "Sign in with any Microsoft account (Outlook/Hotmail)."
step "Click 'Add a site' and enter  https://neelapsychology.co.za/  exactly."
note "If you own the site in Google Search Console, Bing can import everything:"
note "  Settings → Import from Google Search Console → sign in → pick the property."
note "That route copies verification + sitemap automatically and you can then"
note "skim straight through stages 2–3."
pause "Done once your site is added and listed as 'Not Started'."

# ── Stage 2: verification method ──────────────────────────────────────────
stage "Verify ownership"
say "Pick one verification method on your site dashboard."
note "Option A — DNS TXT (recommended, live instantly, no code change):"
note "  copy the TXT record Bing shows and add it at your domain's DNS host."
note "Option B — Meta tag: Bing shows a code like  <meta name=\"msvalidate.01\" ...>"
note "  Copying it below auto-patches this repo and you deploy in stage 3."
ask_secret BING_MSVALIDATE "If using the meta-tag method, paste the value inside content=\"...\" (Enter to skip):"
if [[ -n "$BING_MSVALIDATE" ]]; then
  write_env BING_MSVALIDATE "$BING_MSVALIDATE"
  PERL_CODE="$BING_MSVALIDATE" perl -0pi -e \
    's/(name: "google-site-verification",\s*content: "[^"]*",\n\s*},)/$1\n      { name: "msvalidate.01", content: "$ENV{PERL_CODE}" },/s' \
    "$ROOT_TSX"
  note "meta tag written to $ROOT_TSX"
else
  warn "no meta-tag code — assuming DNS or Google-import route."
fi
pause "Verification method chosen/set."

# ── Stage 3: go live with the change ──────────────────────────────────────
stage "Deploy the repo (if you patched the meta tag)"
if grep -q "msvalidate.01" "$ROOT_TSX"; then
  say "Commit and push so Bing can see the meta tag (Netlify auto-deploys)."
  step "From the repo root run:"
  note "  git add src/routes/__root.tsx .env && git commit -m \"chore: add Bing site verification\" && git push"
  open_url "https://app.netlify.com/sites/jacob-makopo-neelapsych/deploys"
  note "Wait until the Netlify deploy shows 'Published' before continuing."
  pause "Confirm the deploy is live:"
else
  note "No repo change needed (DNS or Google-import verification) — skip."
fi

# ── Stage 4: verify in Bing ───────────────────────────────────────────────
stage "Confirm verification passes"
open_url "https://www.bing.com/webmasters/home"
step "Open your site, click 'Verify' (or refresh the status)."
note "Expected: 'Verified'. If it fails: re-check DNS TXT, or that the meta tag"
note "is live (view source of https://neelapsychology.co.za/ and Ctrl-F msvalidate)."
pause "Once Bing shows your site as Verified."

# ── Stage 5: submit the sitemap ───────────────────────────────────────────
stage "Submit the sitemap"
open_url "https://www.bing.com/webmasters/home"
step "Open your site → left menu → Sitemaps → enter the URL:"
note "  https://neelapsychology.co.za/sitemap.xml"
step "Click Submit, then refresh until it reports 'Submitted'."
note "IndexNow key is already in the repo (public/9355b6074bbafb690b27d749d5ea7472.txt)."
step "Optional sanity check that it's live:"
open_url "https://neelapsychology.co.za/9355b6074bbafb690b27d749d5ea7472.txt"
pause "Sitemap submitted."

# ── Stage 6: live URL submission (fast-track) ─────────────────────────────
stage "Request live indexing"
open_url "https://www.bing.com/webmasters/urlsubmission"
step "Paste these URLs one at a time and submit:"
note "  https://neelapsychology.co.za/"
note "  https://neelapsychology.co.za/about"
note "  https://neelapsychology.co.za/services"
note "  https://neelapsychology.co.za/booking"
note "  https://neelapsychology.co.za/faq"
note "  https://neelapsychology.co.za/contact"
note "Bing also picks these up from the sitemap, so this is a fast-track only."
pause "URLs submitted."

finish
say "After this deploy, also refresh Google's copy of the site:"
step "Google Search Console → URL Inspection → https://neelapsychology.co.za/ → Request indexing"
step "New favicon shows up in Search results after Google recrawls (days to weeks)."